### ISSUE TITLE
How to use the plugin?

### ISSUE THREAD

**Issue by BenSYZ** [hisaknown/jupyterkernel.vim#4]
Thanks for your plugin. Your plugin fulfills all my fantasies about editing jupyter with vim. But unfortunately, I have troubles when using it.

## system information
* Arch Linux 9.2.1+20200130-2
* neovim v0.4.3
* python 3.8.1
* jupyter 4.6.3

`jupyter_kernel_gateway` and `psutil` is at `~/.local/lib/python3.8/site-packages`

## Command

```vim
:JupyterKernelConnect
```

## Observed behavior

```vim
error detected while processing function <SNR>33_connect[2]..jupyterkernel#start_jkg:
line   15:
E117: Unknown function: job_start
E15: Invalid expression: job_start( 'python ' . s:script_dir . '/jupyterkernel/jupyterkernel_client.py ' .  '--vim_port ' . g:jupyterker
nel_port )
```

## What I have tried
I have tried the `debugging` part in `README`

```sh
~ python .config/nvim/plugged/jupyterkernel.vim/autoload/jupyterkernel/jupyterkernel_client.py --vim_port 55555

DEBUG:__main__:Port 42697 found for Jupyter
DEBUG:__main__:Launch Jupyter kernel gateway
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:__main__:{'version': '6.0.3'}
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:__main__:Start VimMessenger
```

and in vim

```vim
:JupyterKernelConnect localhost:55555

Error detected while processing function <lambda>6[1]..<SNR>33_start_kernel:
line    3:
E121: Undefined variable: v:t_channel
(no more errors till I exit vim)
```

The terminal which runs `jupyterkernel_client.py` doesn't give me any log.

## Help wanted
How can I use the plugin, need I run any other command in another concole like the debugging part? I would appreciate it if you could write it in the `README` file.

**Comment by hisaknown** [comment]
I'm sorry but this plugin support only Vim, but not Neovim.  
I'm not going to support Neovim so far, but any contribution is welcome.

If you are interested in editing `ipynb` in vim, [vimpyter](https://github.com/szymonmaszke/vimpyter) would help.
